### ISSUE TITLE
[Bug]: Wrong label on Retweet button

### ISSUE THREAD

**Issue by thekeyboardworrier** [yakisova41/xToTwitter#18]
### Browser

Firefox

### Version

123.0b1

### Release Type

Userscript

### Userscript manager

Tampermonkey 5.0.1

### What is the problem?

Retweet button label shows "Retweets" instead of **Retweet**.

![Free Palestine 🇵🇸](https://github.com/yakisova41/xToTwitter/assets/67034266/13882a4e-0048-468f-9e1d-cd931b8beeb2)

**Comment by yakisova41** [comment]
Fixed v2.3.1
