### ISSUE TITLE
[Request] Revert home icon replacement (bring back the bird house)

### ISSUE THREAD

**Issue by heladeradr** [yakisova41/xToTwitter#21]
In October 10, 2023, the bird house home icon was replaced with a generic home icon. I thought the bird house was cool and fit the Twitter brand. Please bring it back.

I'm adding some possible helpful resources regarding this change:

Dexerto post on the change: https://twitter.com/Dexerto/status/1711807759803711613
3rd party Chrome extension that brings it back:
- Chrome Store page: https://chromewebstore.google.com/detail/twitter-birdhouse/ocbgpahebgjehjfbhmdbonlclalomfka
- GitHub: https://github.com/bvvst/Birdhouse

**Comment by yakisova41** [comment]
This feature has been added to v2.5.0.

**Comment by heladeradr** [comment]
![image](https://github.com/yakisova41/xToTwitter/assets/22121314/d307ddef-f324-4a44-95fc-fcb4a398bc17)
hell yea we got the bridhouse!! tysm!
