### ISSUE TITLE
[Feature Request] Revert redirection to x.com

### ISSUE THREAD

**Issue by win98se** [yakisova41/xToTwitter#27]
### Browser

Microsoft Edge 124.0.2478.105

### Version

2.4.1

### Release Type

Chrome Extension

### What is the problem?

twitter.com is now starting to redirect to x.com instead, and it break almost all things.

![image](https://github.com/yakisova41/xToTwitter/assets/11819816/5d2691ce-9257-4aae-87de-204962855099)

If possible (I don't even know if it's doable though), please (try to) implement the revert of redirection from twitter.com to x.com. Thank you.

**Comment by yakisova41** [comment]
It is indeed impossible to rewrite the domain, even with the Chrome Extension.
Only the registry can do that.
It is possible to rewrite the domain using the navigation API, but it will definitely be unstable.

So, I cannot do it.
Thank you.
