### ISSUE TITLE
[Bug]: Can you support "https://twitter.com/home?mx=1"?

### ISSUE THREAD

**Issue by baio-manbo-sushi** [yakisova41/xToTwitter#38]
### Browser

Chrome 131.0.6778.205

### Version

2.5.0

### Release Type

Chrome Extension

### What is the problem?

![aaaa](https://github.com/user-attachments/assets/81802a0d-b97e-432d-a0c6-a0703bb382a4)
I've been using twitter.com through "?mx=1"(stay on twitter.com not redirecting to x.com), but suddenly Twitter is experiencing infinite loading.
Of course, it's okay to use x.com, but I'm asking just in case.

**Comment by yakisova41** [comment]
Fixed in v3.0.0
