### ISSUE TITLE
[Bug]: Tweet Button

### ISSUE THREAD

**Issue by clsource** [yakisova41/xToTwitter#5]
### Browser

Firefox

### Version

1.6.0

### Release Type

Userscript

### Userscript manager

Tampermonkey

### What is the problem?

The `Tweet` button is now `Post`.

This code could fix it 👍 

```js
Array.from(unsafeWindow.document.getElementsByTagName('span')).forEach(el => {
    if (el.firstChild && el.firstChild.data == "Post") {
        el.innerHTML = "Tweet";
    }
});
```

**Comment by yakisova41** [comment]
v1.8.0, which adds the ability to change from post to tweet, is now available on greasyfork.
