### ISSUE TITLE
[Bug]: Some labels say "Posts" and "Reposts" instead of "Tweet" and "Retweet" respectively

### ISSUE THREAD

**Issue by heladeradr** [yakisova41/xToTwitter#7]
### Browser

Microsoft Edge Version 115.0.1901.203 (Official build) (64-bit)

### Version

@version 1.7.0

### Release Type

Userscript

### Userscript manager

Tampermonkey

### What is the problem?

Tweets are still being called "Posts" by the website. Also making a new tweet is also called a post, retweeting is still called reposting and the tweets tab in my profile still says "Posts".

Please fix this. I want my old twitter back 😭😭

**Comment by yakisova41** [comment]
v1.8.0, which adds the ability to change from post to tweet, is now available on greasyfork.
